import React from 'react';
import { Container, Typography, Box, Paper } from '@mui/material';

const TermsOfService = () => {
  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Paper elevation={3} sx={{ p: 4 }}>
        <Typography variant="h3" component="h1" gutterBottom align="center">
          Terms of Service
        </Typography>
        
        <Typography variant="body2" color="text.secondary" align="center" sx={{ mb: 4 }}>
          Last Updated: {new Date().toLocaleDateString()}
        </Typography>

        <Box sx={{ '& > *': { mb: 3 } }}>
          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              1. Acceptance of Terms
            </Typography>
            <Typography variant="body1" paragraph>
              By accessing and using VidZyme ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              2. Description of Service
            </Typography>
            <Typography variant="body1" paragraph>
              VidZyme is an AI-powered video generation platform that allows users to create videos from text prompts, images, and other media inputs. Our service utilizes artificial intelligence and machine learning technologies to generate video content.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              3. User Accounts and Registration
            </Typography>
            <Typography variant="body1" paragraph>
              To access certain features of our Service, you must register for an account. You agree to:
            </Typography>
            <Typography component="ul" sx={{ pl: 3 }}>
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and promptly update your account information</li>
              <li>Maintain the security of your password and account</li>
              <li>Accept responsibility for all activities under your account</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              4. Acceptable Use Policy
            </Typography>
            <Typography variant="body1" paragraph>
              You agree not to use the Service to:
            </Typography>
            <Typography component="ul" sx={{ pl: 3 }}>
              <li>Create content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or invasive of privacy</li>
              <li>Generate deepfakes or misleading content of real individuals without consent</li>
              <li>Create content that infringes on intellectual property rights</li>
              <li>Generate content for spam, phishing, or fraudulent purposes</li>
              <li>Create content that promotes violence, discrimination, or hate speech</li>
              <li>Attempt to reverse engineer, decompile, or hack the Service</li>
              <li>Use the Service for any commercial purpose without proper licensing</li>
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              5. Intellectual Property Rights
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Your Content:</strong> You retain ownership of any original content you provide to the Service. By using our Service, you grant VidZyme a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and distribute your input content solely for the purpose of providing the Service.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Generated Content:</strong> Videos and content generated by our AI service are owned by you, subject to these Terms. However, you acknowledge that similar content may be generated for other users.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Our Technology:</strong> The VidZyme platform, including all software, algorithms, and AI models, remains our exclusive property.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              6. Payment and Subscription Terms
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Billing:</strong> Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Price Changes:</strong> We reserve the right to modify our pricing with 30 days' notice to existing subscribers.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Cancellation:</strong> You may cancel your subscription at any time. Cancellation will take effect at the end of your current billing period.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              7. Privacy and Data Protection
            </Typography>
            <Typography variant="body1" paragraph>
              Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              8. Content Moderation and Removal
            </Typography>
            <Typography variant="body1" paragraph>
              We reserve the right to review, moderate, and remove any content that violates these Terms or applicable laws. We may suspend or terminate accounts that repeatedly violate our policies.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              9. Disclaimers and Limitations of Liability
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Service Availability:</strong> We strive to maintain service availability but do not guarantee uninterrupted access. The Service is provided "as is" without warranties of any kind.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>AI-Generated Content:</strong> AI-generated content may not always be accurate or appropriate. Users are responsible for reviewing and validating all generated content before use.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Limitation of Liability:</strong> To the maximum extent permitted by law, VidZyme shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or use.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              10. Indemnification
            </Typography>
            <Typography variant="body1" paragraph>
              You agree to indemnify and hold harmless VidZyme from any claims, damages, or expenses arising from your use of the Service, violation of these Terms, or infringement of any rights of another party.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              11. Termination
            </Typography>
            <Typography variant="body1" paragraph>
              We may terminate or suspend your account and access to the Service immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              12. Governing Law and Dispute Resolution
            </Typography>
            <Typography variant="body1" paragraph>
              These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction]. Any disputes arising under these Terms shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              13. Changes to Terms
            </Typography>
            <Typography variant="body1" paragraph>
              We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the new Terms.
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              14. Contact Information
            </Typography>
            <Typography variant="body1" paragraph>
              If you have any questions about these Terms of Service, please contact us at:
            </Typography>
            <Typography variant="body1">
              Email: legal@vidzyme.com<br />
              Address: [Your Business Address]<br />
              Phone: [Your Phone Number]
            </Typography>
          </section>

          <section>
            <Typography variant="h5" component="h2" gutterBottom>
              15. Severability
            </Typography>
            <Typography variant="body1" paragraph>
              If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect.
            </Typography>
          </section>
        </Box>
      </Paper>
    </Container>
  );
};

export default TermsOfService;